### ISSUE TITLE
Both `gvLightScreen`s use the wrong blending mode

### ISSUE THREAD

**Issue by tulip-sudo** [KelvinShadewing/supertux-advance#117]
Both of them should be using `bm_mod` rather than `bm_sub`.
Only reason it works is because `bm_sub` is bugged and does `bm_mod` instead but [this PR corrects it](https://github.com/KelvinShadewing/brux-gdk/pull/44) which will cause this bug to become apparent (it will make the mg, bg, water and some solid layers have their colours inverted)

**Comment by tulip-sudo** [comment]
This is how it looks using my brux PR.
![image](https://user-images.githubusercontent.com/63363329/211166631-9dcef7f7-2fa4-41d1-8b5f-5688c088fb2d.png)

**Comment by KelvinShadewing** [comment]
Applied the fix. Thanks.
