### ISSUE TITLE
Debug functionality that uses the cursor is broken with split screen

### ISSUE THREAD

**Issue by tulip-sudo** [KelvinShadewing/supertux-advance#120]
Debug features with issues:
- Teleport (teleports to wrong location)
- Solid tilemap editor (edits the wrong location)

**Comment by KelvinShadewing** [comment]
Yeah, I haven't added support for split screen to that yet. I'm gonna add that once I fix the other current problems with it.

**Comment by KelvinShadewing** [comment]
Fixed on unstable branch.
