### ISSUE TITLE
Feature: Speedrunning ghosts.

### ISSUE THREAD

**Issue by IoIxD** [KelvinShadewing/supertux-advance#127]
For speedrunning certain levels, it would be very helpful if there was a Mario Kart like ghost, in order to better see what I did for my best time. Speaking of that, it would also be nice to be able to record that ghost, incase I didn't have OBS open when I hit the record.

**Comment by KelvinShadewing** [comment]
We were talking about this request in stream and have come up with a plan on how to do it. Consider this feature confirmed.
