### ISSUE TITLE
Tux glitching in wall when taking damage

### ISSUE THREAD

**Issue by Vankata453** [KelvinShadewing/supertux-advance#2]
In the second level of the game, when Tux hits the top of this enemy when going down, he's getting stuck in the wall and can't get out without resetting the level.

https://user-images.githubusercontent.com/78196474/135306785-231b4ee0-5908-4cc5-9234-8c9186d48a72.mp4

This also happens whenever that enemy is not present on the ground and Tux is getting straight into it.

https://user-images.githubusercontent.com/78196474/135307601-4be1ca51-027a-4d91-98ed-8407bc62fef9.mp4

**Comment by KelvinShadewing** [comment]
It's the Ouchin. I forgot to check ahead of the player before pushing them, since the Ouchin acts as a pseudo-solid object. Just fixed it. Thank you for letting me know!

**Comment by Vankata453** [comment]
No problem! Glad to help! 😀

**Comment by Frostwithasideofsalt** [comment]
wait, when did i reference this issue?!?

**Comment by KelvinShadewing** [comment]
You're putting numbers in your commit messages. If you put # with a number after it, it references an issue. Looks like it might be inserting it automatically somehow.
