### ISSUE TITLE
Save file becomes unusable if you save while moving around on the overworld map

### ISSUE THREAD

**Issue by dtsudo** [KelvinShadewing/supertux-advance#53]
On the overworld, we can save by hitting `PAUSE` -> `Save Game`. This can be done at any time, including as Tux is moving on the path from one level to another.
![image](https://user-images.githubusercontent.com/13825437/156505674-d3a07076-ba7e-4ca5-b63b-15decd083ca9.png)

If we save in such a scenario (where Tux is "between levels"), the save file becomes unusable. Close the game, re-open it, and load the save. Tux is just stuck at his new location :(

**Comment by KelvinShadewing** [comment]
Fixed it.

**Comment by dtsudo** [comment]
Thanks :)
